# Generated by Django 4.0.10 on 2024-01-15 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_organization_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_organization', to='user.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='organization_departments', to='user.department'),
        ),
    ]
