# Generated by Django 4.0.10 on 2024-01-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_department_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
