# Generated by Django 4.0.10 on 2024-01-15 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_section_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.subdepartment'),
        ),
        migrations.AlterField(
            model_name='section',
            name='related_sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sections', to='user.subdepartment'),
        ),
    ]
