# Generated by Django 4.0.10 on 2024-01-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_section_related_sub_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.subdepartment'),
        ),
    ]
