# Generated by Django 4.0.10 on 2024-01-15 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_section_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sub_department',
        ),
    ]
