# Generated by Django 4.0.10 on 2024-01-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_section_sub_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='departments',
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='user.organization'),
        ),
        migrations.AlterField(
            model_name='section',
            name='related_sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.subdepartment'),
        ),
    ]
