# Generated by Django 4.0.10 on 2024-01-16 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_organization_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='organization_departments', to='user.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_organization', to='user.organization'),
        ),
        migrations.AlterField(
            model_name='section',
            name='related_sub_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_sections', to='user.subdepartment'),
        ),
    ]
