# Generated by Django 4.0.10 on 2024-01-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_organization_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='achieved_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
