# Generated by Django 4.0.10 on 2024-01-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_organization_achieved_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criteria_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.criterion')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.department')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.section')),
                ('sub_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subdepartment')),
            ],
        ),
    ]
