# Generated by Django 4.0.10 on 2024-01-18 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_department_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliancereport',
            name='criterion',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='department',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='section',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='sub_department',
        ),
        migrations.DeleteModel(
            name='Criteria',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='achieved_percentage',
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_organization', to='user.organization'),
        ),
        migrations.DeleteModel(
            name='ComplianceReport',
        ),
    ]
