# Generated by Django 4.0.10 on 2024-01-18 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_compliancereport_criterion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='related_sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='user.subdepartment'),
        ),
    ]
