# Generated by Django 4.0.10 on 2024-01-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_subdepartment_related_sub_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='related_sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sections', to='user.subdepartment'),
        ),
    ]
