# Generated by Django 4.0.10 on 2024-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_organization_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='department_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
