# Generated by Django 4.0.10 on 2024-01-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_subdepartment_department_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subdepartment',
            name='department_percentage',
        ),
    ]
